name: GitHub Actions Build and Deploy Demo

on:
  push:
    branches:
      - master

jobs:
  action-test:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Install and Build
        run: |
          python3 -m pip install --upgrade pip
          pip3 install speedtest-cli
          curl ip-api.com
          speedtest-cli